builds:
  -
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64

archives:
  -
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'